services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.11-management
    ports: 
      - "5672:5672"
      - "15672:15672"
  worker:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - db
    command: celery -A src.tasks worker -B
  bot:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbit
      - db
    container_name: bot
    command: python src/bot.py
      